### PR TITLE
add an option to show factories instead of fixtures

### PR DESCRIPTION
**Pull request by nainxo13**
Finished.

I usually use Factories when using rspec, this PR add an option to settings to enable spec/factories support. 

User can enable Factory support by simply adding a line to Settings - User.
default is fixtures as before.

```
{
"fixture_type" : "factories"
}
```

### CODE REVIEW

**Comment by noklesta** [comment]
Hi, since your comment says "Not finished yet", do you still want to add commits? If so, let me know when it's finished. I don't really use Sublime anymore, and not rspec either, so I'm going to have to trust you to test this code. Thanks!

**Comment by nainxo13** [comment]
oh you don't use Sublime anymore? what do you use then? 
If you are going to trust me, I will fix some more stuffs and the feature In PR is not perfect, yet. 
Let me tell you when I'm done!

**Comment by nainxo13** [comment]
I cleaned up some codes and commits, and reopened PR.
The feature is implemented as I wanted, but not sure it's for everyone.
This option is only for users who use rspec and factories.

**Comment by nainxo13** [comment]
I cleaned up commits and rewrote and fix some issues.
Now the feature is implemented as I wanted.
The option is only for people who use rspec with factories.

**Comment by noklesta** [comment]
Great, thanks! To answer your question: I still think Sublime is great, it's just that I work on many different machines and then Vim is more readily available. For projects I normally use IntelliJ (RubyMine or Cursive - I do most of my programming in Clojure these days).

**Comment by nainxo13** [comment]
Thanks! Feels like I should learn Vim someday.

**Pull request merged**
