### PR TITLE
Add preview for the selected file

### PR DESCRIPTION
**Pull request by blueplanet**
I use sublime text 3,and after have selected a file, the cursor is not active. 
By doing so displays a preview when selected, the cursor becomes active well.

after

### CODE REVIEW

**Comment by noklesta** [comment]
Excellent, thanks! Both the preview and the active cursor are great enhancements :)

**Comment by salf** [comment]
If you use two columns layout and continue typing model's name (or controller for example) the cursor will jump to the first file in list and lost focus from file list in dialog box. On the previous commit (320522a6803190468b28596bcaed3f0f9befcb25) this doesn't happened.

**Comment by blueplanet** [comment]
@noklesta Thank you for merge!

**Comment by blueplanet** [comment]
@salf Well certainly. I'll check

**Comment by noklesta** [comment]
I can't seem to prevent the file list from losing focus in a multi-column layout. On the other hand, the inactive cursor problem only occurs with a single-column layout. So, it seems that the best we can do at the moment is to restrict the preview to single-column layout. I have pushed a commit that implements that.

Thanks to both of you, and please let me know if you find a better solution.

**Pull request merged**
